### ISSUE TITLE
Latest CE firmware does weird things with raspbian jessie

### ISSUE THREAD

**Issue by ggnkua** [atarijookie/ce-atari#189] opened 2019-02-22 18:27 UTC
See thread here: http://atari-forum.com/viewtopic.php?f=103&t=35520&p=367853#p367853

It's so weird that in my fresh jessie install everything works great (keyboard, ethernet etc) until I run "ce_update.sh" and then "ce_start" (I actually plugged in a keyboard and hdmi directly to the pi so I can be sure of this).

As a first step maybe roll back the firmware version to a previous version while this is investigated?

**Comment by Atari260STE** [comment] 2019-07-19 21:38
Hi Team,
I've faced an issue with the update CosmosEx v1 (v2 went ok):
http://www.atari-forum.com/viewtopic.php?f=103&t=37103&p=378101#p378101

**Comment by atarijookie** [comment] 2019-07-22 07:55
I've responded there with this - it's related to #199 :

> Hello,
>
> I'm changing the way the update is done on device - it was one zip file with all the 3 binaries for distros (yocto, jessie, stretch), it was more work to do the release when a only a minor thing changed. Now it should work using git downloading only new files, for specific distro only, so releases will be simpler. But as the yocto doesn't have git client on it and the wget contained in that image doesn't support https (while github doesn't let you download without https), the next update of yocto might not be easily possible through internet or might even be the last update. The USB update on yocto still might work, but if you don't have to - just don't update Yocto. 
>
> The new features will probably not be built, added and tested on Yocto, but only on Raspbian Stretch (and possibly older Jessie), as testing and building for 3 platforms instead of 1 is time consuming and annoying. So ideally we should use the latest distro everywhere (if it works - I've seen the mentioned issues with USB or something). 
>
> Regards,
> Jookie
```

**Comment by ggnkua** [comment] 2019-07-22 14:55
Well, I updated both my active devices, a v1 with raspberry pi 1 model b and a v2 with same raspberry pi model (iirc!). Both running raspbian Jessie. For the first I used the ST updater application and for the other I ssh'd to the pi and ran ce_update.sh.

Both seem to have updated fine. But is there something else I should have done? All this talk about git confused me a bit :)

**Comment by atarijookie** [comment] 2019-07-22 15:37
first update would go through the old download-from-web path. the second update will install git (might take 6 minutes) and the will issue 'git pull' when asked for update instead of downloading from web... but from the user point of view it looks almost the same - through ce_conf or by running ce_update.sh

**Comment by ggnkua** [comment] 2019-07-22 16:26
Well, as an addendum to my report above, I'm sad to report that my V1 device went fubar again :/

The MegaSTE can connect to it fine via acsi, but network is unresponsive (was working before the update, as I did web update) and usb is also down as when I plug in a keyboard it does not show any keystrokes on screen. Actually I double checked that - I started typing random characters while raspbian was booting and input froze around the time it tried to bring up ethernet.

So it seems I either have to get a newer raspberry pi (this is probably the first one - it has 2 usb ports) or just not upgrade that device (after re-writing raspbian from scratch)...

**Comment by atarijookie** [comment] 2019-07-23 08:50
Thank you, @ggnkua, I will have to investigate why it's behaving badly on v1 device. In the ideal situation we will have one Raspbian (Stretch, which is newer than Jessie) running on all the devices...

**Comment by ggnkua** [comment] 2019-07-23 14:34
Well, when I re-read my post above I got cold feet and booted the pi again. It is indeed raspbian jessie. (I'm confusing debian versions - I thought jessie was the latest. What's wrong with people not using version numbers instead of "cute" nicknames? :P)

Anyway, I tried the same experiment as above, kept mashing the keyboard till it stopped outputting characters on screen. It seems to stop at the time it displays ```set console font and keymap...``` and ```started lsb: raise network interface...``` and ```starting ifup of eth0...```.

I think I'll just go ahead and flash stretch and try again. As @atarijookie says: there's no reason for supporting many operating systems, just one flavour should be more than enough!

**Comment by ggnkua** [comment] 2019-07-23 16:17
It gets curiouser and curiouser...

Downloaded a fresh stretch image, flashed it on the sd card, booted the pi.... and console/network is frozen without even updating.

BTW if it's not clear from the above: The ST can talk to the CosmosEx without issues and you can change settings from ce_conf.prg etc. But no matter what I do it cannot connect to the network (ethernet) and plugging a usb keyboard on the pi has no effect on the console.

I suppose that eventually I'll just have to take the plunge and buy a few raspberry pi 2 or 3 and replace the v1s I got installed here. It's just inconvenient is all.

**Comment by ggnkua** [comment] 2019-07-23 17:06
Just flashed the pi with a fresh jessie image and it's back to normal.

Now, call me Mr unadventurous but I'll leave it be for now :D.

**Comment by atarijookie** [comment] 2019-07-23 19:12
> Downloaded a fresh stretch image, flashed it on the sd card, booted the pi.... and console/network is frozen without even updating.

Yes, this is probably because I've updated and uploaded the Stretch image yesterday... 

> Just flashed the pi with a fresh jessie image and it's back to normal.

Because that one is not updated and I'm not planning to update it.

> I suppose that eventually I'll just have to take the plunge and buy a few raspberry pi 2 or 3 and replace the v1s I got installed here.

No, don't do that - they have differently placed USB and ethernet connectors plus the internal connector is different, so they won't fit in the device.

I've just made some tests with Stretch + RPi 1 and the keyboard and ethernet is indeed not working after boot. I see the ethernet LEDs on RPi blink fine during boot, but once the Franz / Hans activity LEDs blink (the CE app has started), the ethernet LEDs turn off. I was suspecting core_freq=250 in config.txt to be doing this, but this seems like it's done by app. And I also have a guess why - it's probably caused by accessing pins, which aren't on GPIO on RPi 1 (it has only 26 pins) but on RPi 3 are available and are used by OLED display, button and buzzer. This issue won't probably happen on Yocto as the code for this is disabled by compilation for Yocto, but on Jessie and Stretch it's enabled and on RPi 1 are probably used to controll the eth + USB... 

To confim this, I'll disable the extra pins usage, recompile, see if the USB + eth problem disappears. If it does, then I'll make a fix - detection of RPi 1 from code (there is already something for that there), and on RPi 1 then won't touch the extra (non-user) GPIO pins.... Stay tuned.

**Comment by mikrosk** [comment] 2019-07-23 19:14
@ggnkua I know this takes you back from your grandpa wheelchair ;) but maybe you could try the official https://www.raspberrypi.org/downloads/raspbian/ ? Just to be sure something didn't break it on CE side.

EDIT: Oh I see, it's most likely a CE issue after all.

**Comment by atarijookie** [comment] 2019-07-23 19:50
GPIO6 on RPI 1 is eth+usb reset, on RPI 3 its used by the mentioned new features of CE v3:
https://electronics.stackexchange.com/questions/140485/lan9512-usb-hub-and-ethernet-controller-problems

**Comment by atarijookie** [comment] 2019-07-24 04:54
I've made a fix and tested it on Stretch + RPi 1, the ethernet + USB now works after the boot. It was the mentioned issue with the GPIO vs LAN chip..

https://github.com/atarijookie/ce-atari/commit/052882d861bba76ec7ca34bfb5ed6e3cd8b550c5

The Stretch image on my web isn't updated yet, I will do it during the day (from the place where internet is faster than at my home ;) ), I will let you know after that...

**Comment by atarijookie** [comment] 2019-07-24 08:50
The new Raspbian Stretch image is on my web page, try it and report how it went...

**Comment by ggnkua** [comment] 2019-08-02 19:07
My comments [here](https://github.com/atarijookie/ce-atari/issues/199#issuecomment-517812004) are relevant here too I'm sure

**Comment by atarijookie** [comment] 2019-08-08 04:36
The dead usb and network issue has been fixed, closing.

**Closed as completed by atarijookie** 2019-08-08 04:36 UTC
