### ISSUE TITLE
IKBD emulated keyboard key(s) get stuck as pressed after restart

### ISSUE THREAD

**Issue by atarijookie** [atarijookie/ce-atari#7] opened 2016-04-14 08:02 UTC
Adam Klobukowski reports:

It seems, that sometime, keyboard state remains after power cycle. I'm playing with remote api atm. and it might be related to this. This sound strange, but happens to me a lot.

Some background
I'm using CE to remotely control STE, to record SNDH tunes into mp3s. I do this using STj player on STE and control it from PC via CE api, I want to encode whole archive, so I have it scripted. Of course, SNDH files are not perfect, and I have to powercycle often. After powercycle, often STE wakes with key pressed down.

I found a workaround for the bug: I send 'up' event for each key, after I turn on ST (using aditional Raspi magic ;)) and this fixes it.

**Comment by tin-nl** [comment] 2016-04-14 08:28
I'll have a look if the Rest API has some state here. Doubt it, but possible.

**Comment by tin-nl** [comment] 2016-04-17 11:03
Asked the original reporter what included the power cycle exactly. 
STe and CE were power cycled at the same time. Unfortunately he has no logs of this.

There goes the "some state left" idea. IKBD as well as ce_main as well as TOS should have resetted their state then.

Next question: did this happen without any involvement of the Rest API or the physical keyboard during powerup?

Also: TOS might send some initialization commands to the IKBD on powerup (probably setting mouse to relative mode or sth like that or send a reset command), have to check. Maybe these get through only partially due to ce_main not ready to forward them to the IKBD then?

**Comment by tin-nl** [comment] 2016-04-17 18:49
Confirmed: TOS sends $8001 (IKBD reset) and IKBD should answer with $F1 (latter not tested).
GEM sends on initialization $08 (Relative mouse mode), $0B0101 (Mouse Threshold 1,1), $10 (Y=0 on top), $0700 (default mouse button mode).

**Comment by tin-nl** [comment] 2016-04-17 18:53
@Jookie: what exactly happens, if CE doesn't relay IKBD commands? Does Bit 1 of $ffffc00 (=Tx data register empty) remain 0? Nothing is transmitted, after all...
If so, TOS blocks at the first ikbdws call until this bit gets 1 (AKA ce main app getting ready).

**Comment by atarijookie** [comment] 2016-04-18 12:06
My guess is that the TX empty flag or something similar should work the same no matter if there is something connected (answering) or not, as this only indicates that hardware was able to push one byte out of the serial line. 

When CE is down (either just the linux app, or the whole device), the commands are not handled, so even that 0x8001 command will not be registered. 

There could be an improvement for Franz, which would directly resend IKDB data back if it isn't configured by linux app, to allow faster keyboard + mouse usage, when device is starting, but preinit app would need to bring Franz up. 

IKBD stuff needs more fixing, it was mentioned here:
[Issue 16](https://github.com/atarijookie/ce-atari/issues/16)

**Comment by tin-nl** [comment] 2016-04-25 18:14
Here's an interresting case. While testing CE_STiNG, I saw several keyboard failures (via CE IKBD injector) that manifest themselves in an unresponsive keyboard and mouse (on ST as well as remote).
A few checks later, I had a reproducable case: start Bugaboo, enter "reset" (or try to), see "r" repeating endlessly until ce_main is restarted.
The gist:

```
==>KeyDown: R
EV_KEY: code 19, value 1, stKey: 13
01273779    00000000     sending to ST: 13 
01273790    00000011     Ikbd::processStCommands -- got command 13, len: 1, cb contains 1 bytes
==>WOWOWOW! This shouldn't happen, we get KeyUp: R, no STCMD_PAUSE_OUTPUT  
01273791    00000001     Ikbd::processStCommands -- ST says: STCMD_PAUSE_OUTPUT
```

This is a Mega ST with TOS 1.02, the CE is v1 with patched resistor. Running on Yocto, latest update (2016-04-24).

So normal keypresses are interpreted as IKBD commands, so ce_main just stops sending keycodes after a press of "R".

It boils down to this:

```
==>ST turned off, CE powercycled

00010541        00010541         ----------------------------------------------------------
00010571        00000030         ikbdThreadCode will enter loop...
00010572        00000001         Got device (/tmp/vdev/keyboard): /tmp/vdev/kbd
00010573        00000001         Got device (/tmp/vdev/mouse): /tmp/vdev/mouse
00013581        00003008         Got device (keyboard): /dev/input/event0

==>ST turned on

00082532        00068951         sending to ST: f1
00082544        00000012         Ikbd::processStCommands -- got command f1, len: 0, cb contains 1 bytes
00082545        00000001         Ikbd::processStCommands -- not GET cmd, and we don't know what to do
00084120        00001575         Ikbd::processStCommands -- got command 00, len: 0, cb contains 1 bytes
00084121        00000001         Ikbd::processStCommands -- not GET cmd, and we don't know what to do
00084184        00000063         sending to ST: f1
00084196        00000012         Ikbd::processStCommands -- got command f1, len: 0, cb contains 1 bytes
00084197        00000001         Ikbd::processStCommands -- not GET cmd, and we don't know what to do
00091207        00007010         Ikbd::processStCommands -- got command 00, len: 0, cb contains 1 bytes
00091209        00000002         Ikbd::processStCommands -- not GET cmd, and we don't know what to do
00091910        00000701         Ikbd::processStCommands -- got command 00, len: 0, cb contains 1 bytes
00091911        00000001         Ikbd::processStCommands -- not GET cmd, and we don't know what to do
00104902        00012991         Ikbd::processStCommands -- got command 00, len: 0, cb contains 1 bytes
00104903        00000001         Ikbd::processStCommands -- not GET cmd, and we don't know what to do

==>KeyDown R

00115178        00010275         sending to ST: 13
00115190        00000012         Ikbd::processStCommands -- got command 13, len: 1, cb contains 1 bytes
00115192        00000002         Ikbd::processStCommands -- ST says: STCMD_PAUSE_OUTPUT

==>IKBD stops

00115265        00000073         sending to ST: 93
00115439        00000174         sending to ST: 12
00115502        00000063         sending to ST: 92
00115676        00000174         sending to ST: 1f
00115770        00000094         sending to ST: 9f
00115974        00000204         sending to ST: 12
00116067        00000093         sending to ST: 92
00116282        00000215         sending to ST: 14
00116334        00000052         sending to ST: 94
```

Do you have any idea why all Keycodes are interpreted as commands? Also: why does the log start with $F1 and not with $8001? Do we look at a software or a hardware problem? 

This doesn't happen with V2 (never had an unresponsive keyboard/mouse there) and does not seem to happen with another V1 in an STE.

**Comment by tin-nl** [comment] 2016-04-25 18:45
(Btw, just tested - same device, same injector and keyboard work flawlessly on a MSTE)

**Comment by atarijookie** [comment] 2016-04-25 22:22
Wow, that's crazy... I can't say out of my head if the behavior could be improved on the problematic machine, but it sounds like the resistor patch didn't help completely, and with combination with some IKBD emulation bug it fails miserably. 

The first thing I would to help with this is that IKBD 'unit' test mentioned before in the issue #16 , that could accidentally fix the thing ;) and if not, it would at least get me refreshed on the topic of IKBD...

**Comment by tin-nl** [comment] 2016-04-26 09:06
I'll test this on another Mega ST. AFAIR I had the same behaviour on an STE too back when there was no ikbdlog - unfortunately the DMA there is seriously shot (bit flips, so no ACSI boot and some chars/bytes appear changed opposing to the original disk content), so I can't test that one.

**Comment by mikrosk** [comment] 2017-01-02 04:58
Having played with my STE and IKBD for tens of hours I can't say I am able to reproduce it. RESET is handled correctly and 'R' is definitely not interpreted as PAUSE. Candidate for close?

**Comment by mikrosk** [comment] 2017-01-02 05:00
@tin-nl :

> Also: why does the log start with $F1 and not with $8001? Do we look at a software or a hardware problem?

$F1 is an answer to $80, $01 sequence. I.e. the ST sends RESET ($80, $01) and the IKBD replies with $f1 (OK, version number 1). However, power up is also considered a RESET, therefore you get $f1 even without $80, $01 sent first.

**Comment by tin-nl** [comment] 2017-01-02 09:01
@mikrosk: Thanks for the clarification, I was under the impression TOS sends a $8001 at boot.

Do you have a V1 (first version with wrong resisitor)? I don't think this happens with V2, but have to retest.

**Comment by tin-nl** [comment] 2017-01-02 09:09
> I was under the impression TOS sends a $8001 at boot.

Just checked the TOS source - I rememberred correctly, it does send $8001 right before cartridge execution. It should have showed up in the log, hence my surprise.

**Comment by mikrosk** [comment] 2017-01-02 09:10
> I was under the impression TOS sends a $8001 at boot.

It does -- only for the first time (power cycle) it is no needed. So you see $F1 twice -- power up and reset from TOS. And yes, it does show up in the logs. :)

> Do you have a V1 (first version with wrong resisitor)? I don't think this happens with V2, but have to retest.

Surely V2. That "V1" I mentioned is related to IKBD protocol version number (interestingly, the IKBD manual mentions it should be 0xF0, therefore it's really a revised version).

**Comment by tin-nl** [comment] 2017-01-02 09:13
@mikrosk: Then I probably snipped that, don't remember :)

Then I'll recheck with V1 (yocto) and V2 (raspbian). Until then I tag this V1 hardware so we don't get confused.

**Comment by tin-nl** [comment] 2017-01-02 09:15
> (interestingly, the IKBD manual mentions it should be 0xF0, therefore it's really a revised version).

AFAIR there is only one IKBD ROM version known. Would be interresting to see revision 0 :)

**Comment by mikrosk** [comment] 2017-02-28 04:01
Nobody's complaining, closing then.

**Closed as completed by mikrosk** 2017-02-28 04:01 UTC
Labels: bug, IKBD
